var1 = "54" #String(str)
var4 = "32"
var2 = 4 #Integer(int)
var3 = 36.7 #Decimal(float)
# print(int(var1))
# print(type(var1))
# print(50 * "Hello World\n")
# bar = input()
# print("Enter your Number")
# print("You Entered",int(bar)+10)
print("Enter your First Number")
a = input()
print("Enter your Second Number")
b = input()
print("Sum of These Two Numbers",int(a) + int(b))